### PR TITLE
Fix bluetooth

### PR DESCRIPTION
**Pull request by nikhil93uf**
Change-Id: I52e1787a4b9a1a06dd4e4bb093b2d77d49bf503d

Your previous update to wcnss_filter broke Bluetooth. This restores the binary to an earlier version.

### CODE REVIEW

**Comment by HashBang173** [comment]
We do not accept pull requests, so I pushed your commit via gerrit: http://gerrit.aicp-rom.com/#/c/16651
https://github.com/AICP/proprietary_vendor_motorola/commit/46adcffd21c6b2c3fe88318ee7db8a3240a81731

**Comment by nikhil93uf** [comment]
Ah yes. Thank you.

**Comment by Zipsnet** [comment]
NOOOOO!!! He's a gator ;)

**Comment by nikhil93uf** [comment]
Haha. Glad to see another Gator here.

**Pull request merged**
